#!/usr/bin/env bash

#git branch -m master main
#git push -u origin main

git checkout master
git branch -m master main
git fetch
git branch --unset-upstream
git branch -u origin/main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
git push -u origin main
