#!/usr/bin/env bash
#
# "Archive" the current branch
#
# Once a feature branch has been code reviewed, approved, and merged,
# tag it in it's current state and save it for later.
#

local_branch="$(git whereami)"
readonly local_branch
readonly archive_branch="archive/${local_branch}"
upstream="${1:-origin}"

main() {
	archive_tag
	remove_archived_branch
}

archive_tag() {
	git tag "${archive_branch}"
	git push "${upstream}" "${archive_branch}"
}

remove_archived_branch() {
	git checkout master

	#local
	git branch -d "${local_branch}"

	#upstream
	git push origin --delete "${local_branch}"
}

help() {
	cat <<EOF
Usage: git branch-archive [upstream]
Tag the current branch as archived and delete it locally and remotely.
If no upstream is specified, 'origin' is used.
EOF
	# completions are provided centrally in `completions/`
}

_git_branch_archive() {
	if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
		help
		exit 0
	fi

	main "$1"
}

_git_branch_archive "$@"
